name: Deploy SIEM Rules

on:
  push:
    branches: [main]
    paths:
      - 'splunk/**'
      - 'qradar/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Python qur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Asiliylqlari qur
        run: pip install requests urllib3

      - name: Deploy et
        env:
          GH_TOKEN:      ${{ secrets.GH_TOKEN }}
          GH_REPO_OWNER: ${{ secrets.GH_REPO_OWNER }}
          GH_REPO_NAME:  ${{ secrets.GH_REPO_NAME }}
          GH_BRANCH:     main
          SPLUNK_HOST:   ${{ secrets.SPLUNK_URL }}
          SPLUNK_TOKEN:  ${{ secrets.SPLUNK_TOKEN }}
          SPLUNK_APP:    search
          QRADAR_HOST:   ${{ secrets.QRADAR_URL }}
          QRADAR_TOKEN:  ${{ secrets.QRADAR_TOKEN }}
        run: python scripts/siem_api_sync.py
